// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v3.20.3
// source: lib.proto

/* eslint-disable */

/** TransactionStatus: Enum representing the possible statuses of a transaction. */
export enum TransactionStatus {
  PENDING = 0,
  PROCESSING = 1,
  FAILED = 2,
  COMPLETE = 3,
  UNRECOGNIZED = -1,
}

export interface Empty {}

export interface PaginatedRequest {
  /** Page offset to start from */
  page: number;
  /** Number of items to be return per page */
  size: number;
}
