// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v3.20.3
// source: lightning.proto

/* eslint-disable */

export interface Bolt11 {
  /** Bolt11 lightning invoice */
  invoice: string;
}

export interface FmInvoice {
  /** Fallback invoice */
  invoice: string;
  operationId: string;
}
