/** TransactionStatus: Enum representing the possible statuses of a transaction. */
export enum TransactionStatus {
  PENDING = 0,
  PROCESSING = 1,
  FAILED = 2,
  COMPLETE = 3,
  MANUAL_REVIEW = 4,
  UNRECOGNIZED = -1,
}

export enum TransactionType {
  DEPOSIT = 0,
  WITHDRAW = 1,
  WALLET_CREATION = 2,
  UNRECOGNIZED = -1,
}

/** Currency: Enum representing supported currencies. */
export enum Currency {
  BTC = 0,
  KES = 1,
  UNRECOGNIZED = -1,
}

export type Empty = object;

export interface PaginatedRequest {
  /** Page offset to start from */
  page: number;
  /** Number of items to be return per page */
  size: number;
}

export interface FindTxRequest {
  txId: string;
  userId?: string | undefined;
}

export interface OnrampSwapSource {
  /** Currency code for the target currency */
  currency: Currency;
  /** Target destination */
  origin: MobileMoney | undefined;
}

export interface OnrampSwapTarget {
  /** Lightning protocol payout */
  payout: Bolt11 | undefined;
}

export interface OfframpSwapTarget {
  /** Currency code for the target currency */
  currency: Currency;
  /** Mobile money payout destination */
  payout: MobileMoney | undefined;
}

export interface MobileMoney {
  /** Phone number for the mobile money offramp */
  phone: string;
}

export interface Bolt11 {
  /** Bolt11 lightning invoice */
  invoice: string;
}

export interface FmLightning {
  invoice?: string | undefined;
  operationId?: string | undefined;
  lnurlWithdrawPoint?: LnUrlWithdrawPoint | undefined;
}

/**
 * Message returned as `FmLightning`
 * when a user want's to withdraw from Bitsacco wallet via LNURL
 *
 * REF: https://github.com/lnurl/luds/blob/luds/03.md step 3
 */
export interface LnUrlWithdrawPoint {
  /** The LNURL bech32 encoded string to be encoded as QR code */
  lnurl: string;
  /** Key used for withdrawal (k1 parameter) */
  k1: string;
  /** URL that will handle the withdrawal callback */
  callback: string;
  /** When the withdrawal request expires (Unix timestamp) */
  expiresAt?: number | undefined;
}

/**
 * Message serializing request parameters from GET request
 * to bitsacco LNURL service `callback`
 *
 * REF: https://github.com/lnurl/luds/blob/luds/03.md step 5
 */
export interface LnUrlWithdrawPointCall {
  /** Key used for withdrawal (k1 parameter) */
  k1: string;
  /** This is a payment request (pr parameter) generated by user `LN WALLET` */
  payout: Bolt11 | undefined;
}

export interface CustomStore {
  get(key: string): Promise<any>;
  set(key: string, value: any, ttl?: number): Promise<void>;
}

/**
 * Request object for processing LNURL withdrawals
 *
 * REF: https://github.com/lnurl/luds/blob/luds/03.md
 */
export interface LnUrlWithdrawRequest {
  /**
   * The k1 parameter used to identify the withdrawal request
   * Sent on first and second steps of handshake
   */
  k1: string;
  /**
   * The type of LNURL. Always = 'withdrawRequest'
   * Sent in first step of handshake
   */
  tag?: string | undefined;
  /**
   * The LNURL callback confirmation
   * Sent in first step of handshake
   */
  callback?: string | undefined;
  /**
   * The maximum withdrawable amount msats confirmation
   * Sent in first step of handshake
   */
  maxWithdrawable?: string | undefined;
  /**
   * The minimum withdrawable amount msats confirmation
   * Sent in first step of handshake
   */
  minWithdrawable?: string | undefined;
  /**
   * The default description confirmation
   * Sent in first step of handshake
   */
  defaultDescription?: string | undefined;
  /**
   * The bolt11 invoice from the receiving wallet (the "pr" parameter).
   * Sent on second step of handshake
   */
  pr?: string | undefined;
}

/**
 * Message returned from  `LnUrlWithdrawPoint.callback`
 * when a user's `LN WALLET` makes a GET request with invoice and params
 * REF: https://github.com/lnurl/luds/blob/luds/03.md step 3 and step 6
 */
export interface LnUrlWithdrawResponse {
  /**
   * The type of LNURL. Always = 'withdrawRequest'
   * Sent in RESPONSE to first step of handshake
   */
  tag?: string | undefined;
  /**
   * The LNURL callback confirmation
   * Sent in RESPONSE to first step of handshake
   */
  callback?: string | undefined;
  /**
   * The k1 parameter used to identify the withdrawal request
   * Sent in RESPONSE to first step of handshake
   */
  k1?: string | undefined;
  /**
   * The maximum withdrawable amount msats confirmation
   * Sent in RESPONSE to first step of handshake
   */
  maxWithdrawable?: string | undefined;
  /**
   * The minimum withdrawable amount msats confirmation
   * Sent in RESPONSE to first step of handshake
   */
  minWithdrawable?: string | undefined;
  /**
   * The default description confirmation
   * Sent in RESPONSE to first step of handshake
   */
  defaultDescription?: string | undefined;
  /**
   * "OK" or "ERROR"
   * Sent in RESPONSE to second step of handshake
   */
  status?: string | undefined;
  /**
   * error reason if `status` = "ERROR"
   * Sent in RESPONSE to second step of handshake
   */
  reason?: string | undefined;
}
